name = "Ol' Reliable Fabric"
author = "LittlePerson101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[download]
url = "https://raw.githubusercontent.com/LittlePerson101/Ol-Reliable-Modpack-Modrinth/1.21.x/pack.toml"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d8d977ed81eee9f98f32e97aada23c17212767f34eec40025ab54dbb183100"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.11", "1.21.10", "1.21.8", "1.21.7", "1.21.6", "1.21.5", "1.21.4", "1.21.3", "1.21.1", "1.21"]
