name = "Ol' Reliable Fabric"
author = "LittlePerson101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[download]
url = "https://raw.githubusercontent.com/LittlePerson101/Ol-Reliable-Modpack-Modrinth/1.21.x/pack.toml"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8259b5200e138547628af51e9e737dba4c03bb70f6936e87155e3eb285bbe63d"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.11", "1.21.10", "1.21.8", "1.21.7", "1.21.6", "1.21.5", "1.21.4", "1.21.3", "1.21.1", "1.21"]
